kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: vsphere-infra
  name: vsphere-ptr-record  
spec:
  selector:
    matchLabels:
      app: vsphere-ptr-record
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vsphere-ptr-record
    spec:
      volumes:
        - name: creds
          secret:
            secretName: build02-kubeconfig
      containers:
        - name: container
          volumeMounts:
            - mountPath: "/creds"
              name: creds
          env:
            - name: KUBECONFIG
              value: /creds/build02-kubeconfig
          image: 'quay.io/ocp-splat/vsphere-ptr-record:latest'
          ports:
            - containerPort: 53
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ''
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
