kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: vsphere-ptr-record  
spec:
  selector:
    matchLabels:
      app: vsphere-ptr-record
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vsphere-ptr-record
    spec:
      containers:
        - name: container
          image: 'quay.io/ocp-splat/vsphere-ptr-record:latest'
          ports:
            - containerPort: 5353
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: secret-check
          image: 'quay.io/ocp-splat/vsphere-ptr-record:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          command: 
          - /bin/sh
          args:
          - ./secret-check.sh
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ''
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
